networks:
  net:
    external: true
    name: network

services:
  gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - net

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database_all:5555/postgres_db
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - net


  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database_all:5555/postgres_db
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_MAIN_LAZY_INITIALIZATION=true
    networks:
      - net



  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    ports:
      - "8085:8085"
    environment: # Теперь отступ правильный (2 пробела от края сервиса)
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database_all:5555/postgres_db
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_MAIN_LAZY_INITIALIZATION=true
    networks:
      - net


  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database_all:5555/postgres_db
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_MAIN_LAZY_INITIALIZATION=true
    networks:
      - net


