server:
  port: 8080


spring:
  application:
    name: api-gateway
  config:
    import:
      - optional:file:common-yml/application-logging.yml
  cloud:
    gateway:
      routes:
        # 1. Публичный маршрут для регистрации (БЕЗ TokenRelay)
        - id: user-registration
          uri: http://user-service:8081
          predicates:
            - Path=/api/users/register, /auth/**
        - id: virtual-test
          uri: http://virtual-service:8088
          predicates:
            - Path=/api/virtual/**
          # Здесь НЕ пишем TokenRelay

        # 2. Защищенный маршрут для профиля и прочего (С TokenRelay)
        - id: user-service-protected
          uri: http://user-service:8081
          predicates:
            - Path=/api/users/**
          filters:
            - TokenRelay=

        - id: order-service
          uri: http://order-service:8085
          predicates:
            - Path=/api/orders/**
          filters:
            - TokenRelay=

        - id: product-service
          uri: http://product-service:8084
          predicates:
           - Path=/api/products/**



# Actuator endpoints для мониторинга
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always