spring:
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      observation-enabled: true
      batch-size: 16384
      buffer-memory: 33554432
      # Указываем, что ключ — строка, а значение — JSON
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        # Эта настройка важна, чтобы Jackson не добавлял лишние заголовки типов
        spring.json.add.type.headers: true
        linger.ms: 10

    consumer:
      observation-enabled: true
      group-id: ${spring.application.name}-group
      auto-offset-reset: earliest
      # Указываем, как читать JSON обратно в объект
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        # Доверяем всем твоим пакетам, чтобы разрешить десериализацию
        spring.json.trusted.packages: "*"
    listener:
      observation-enabled: true
      concurrency: 3

