spring:
  datasource:
    url: jdbc:postgresql://database:5555/postgres_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 110
      minimum-idle: 5
      connection-timeout: 15000
      leak-detection-threshold: 2000


  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update  # ← это правильно (на уровне jpa.hibernate)
    show-sql: true
    properties:
      hibernate:
      generate_statistics: true
      format_sql: true


  liquibase:
    enabled: false
    change-log: classpath:liquibase/changelog-master.yml

  threads:
    virtual:
      enabled: true
