spring:
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      retries: 3
      properties:
        retry.backoff.ms: 1000
        delivery.timeout.ms: 120000
        enable.idempotence: true
      acks: all
    listener:
      concurrency: 3
    batch-size: 16384
    buffer-memory: 33554432
    linger.ms: 10
    consumer:
      group-id: ${spring.application.name}-group
      auto-offset-reset: earliest
      enable-auto-commit: true