logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr([%15.15t]){magenta} %clr(%-5p) %clr(%-40.40logger{39}){cyan} %clr(:){faint} %clr([ID:%X{requestId}]){yellow} %msg%n"
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: INFO
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
    org.springframework.transaction: INFO
    com.oz.gateway: DEBUG
    org.springframework.cloud.gateway: INFO
    org.springframework.security: INFO