spring:
  datasource:
    url: jdbc:postgresql://database:5555/postgres_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: update  # ← это правильно (на уровне jpa.hibernate)
    show-sql: false
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true

  liquibase:
    enabled: false
    change-log: classpath:liquibase/changelog-master.yml
