server:
  port: 8081

spring:
  application:
    name: user-service
  config:
    import:
      - optional:file:common-yml/application-keycloak.yml
      - optional:file:common-yml/application-postgres.yml
      - optional:file:common-yml/application-logging.yml
logging:
  level:
    com.oz.user: DEBUG
    org.hibernate.SQL: DEBUG