server:
  port: 8085
spring:
  application:
    name: order-service
  config:
    import:
      - optional:file:common-yml/application-keycloak.yml
      - optional:file:common-yml/application-postgres.yml
      - optional:file:common-yml/application-kafka.yml



