server:
  port: 8084

spring:
  application:
    name: product-service
  config:
    import:
      - optional:file:common-yml/application-redis.yml
      - optional:file:common-yml/application-keycloak.yml
      - optional:file:common-yml/application-postgres.yml
      - optional:file:common-yml/application-kafka.yml
      - optional:file:common-yml/application-logging.yml

